name: example

environment:  
  sdk: ">=2.6.1 <3.0.0"

dependencies:
  #todo: change this to pub version if I release this
  mock_creator_annotation:
    path: ../mock_creator_annotation/

dev_dependencies:
  build_runner: ^1.7.3
  test: ^1.9.3
  mock_creator_generator:
    path: ../mock_creator_generator/

