name: example

environment:  
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  mock_creator_annotation:
    path: ../mock_creator_annotation
  quiver_hashcode:
    git: https://github.com/atreeon/quiver_hashcode

dev_dependencies:
  test: ^1.24.3
  build_runner: ^2.3.3
  mock_creator_generator:
    path: ../mock_creator_generator/
