linter:
  rules:
    camel_case_types: false

analyzer:
  strong-mode:
    implicit-casts: false
#    implicit-dynamic: false



#include: package:pedantic/analysis_options.yaml

#linter:
# rules:
#   avoid_shadowing_type_parameters: false