name: mock_creator_generator
description: Creates a mock for classes with a single call method making it easy for us to create those mocks automatically.
version: 1.0.4
homepage: https://github.com/atreeon/MockCreator
 
environment:  
  sdk: ">=2.6.1 <3.0.0"
  
dependencies:  
  build: ^1.2.2
  source_gen: ^0.9.4+7
  mock_creator_annotation: ^1.0.1
  dartx: ^0.3.0
  quiver: ^2.0.1
  dartz: ^0.8.3
  basic_utils: ^2.4.8
  analyzer: '>=0.39.5 <0.40.0'
  meta: ^1.1.8

dev_dependencies:  
  build_runner: ^1.7.3
  test: ^1.11.1
  