name: mock_creator_generator
description: Creates a mock for classes with a single call method making it easy for us to create those mocks automatically.
version: 1.0.14-nullsafety
homepage: https://github.com/atreeon/MockCreator

environment:
  sdk: ">=2.7.2 <3.0.0"

dependencies:
  meta: ^1.1.8
  analyzer_models: ^1.0.3
  build: ^1.2.2
  source_gen: ^0.9.4+7
  mock_creator_annotation: ^1.0.2-nullsafety3
  analyzer: '>=0.40.0 <0.42.0'

dev_dependencies:
  build_runner: ^1.7.3
  test: ^1.11.1
