name: mock_creator_generator
description: Creates a mock for classes with a single call method making it easy for us to create those mocks automatically.
version: 1.0.16
homepage: https://github.com/atreeon/MockCreator
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  analyzer: '>=1.7.0 <=4.4.0'
  build: ^2.1.1
  source_gen: ^1.1.1
  generator_common:
    git:
      url: https://github.com/atreeon/generator_common
      ref: master
  meta: ^1.1.8
  mock_creator_annotation:
    git:
      url: https://github.com/atreeon/MockCreator.git
      path: mock_creator_annotation
      ref: master

dependency_overrides:
  mock_creator_annotation:
    path: ../mock_creator_annotation

dev_dependencies:
  test: ^1.24.3
  build_runner: ^2.3.3